// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpjwxvediooxnljkqdru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwand4dmVkaW9veG5samtxZHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTQzMzMsImV4cCI6MjA1NjkzMDMzM30.lXS7HcIVBWWKSP_Z6hYq22jlBK6XGqyBcrdTJwFwjPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);